FROM node:22-bookworm

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci

COPY prisma ./prisma
COPY tsconfig.json ./
COPY src ./src

RUN npx prisma generate && npm run build

EXPOSE 4000

CMD ["sh", "-c", "npx prisma db push && npm run prisma:seed && npm run start"]
